site_name: Bolt Runtime Engine Documentation
site_description: Official documentation for the Bolt programming language
site_author: Swifteex Studio

docs_dir: docs

nav:
  - Native syntax: index.md
  - Usage of modules in bolt: modules.md
  - Bfile: bfiledocs.md

theme:
  name: material
  palette:

    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code
  - codehilite